"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Eye, FileDown, Plus, RefreshCw, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button"; import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"; import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { ApiError } from "@/lib/api/client"; import { listQuestions, type Question } from "@/lib/api/questions"; import { addSection, createExport, deleteSection, downloadExport, getExport, getPaper, putSectionQuestions, updatePaper, updateSection, type PaperDetail, type PaperQuestion, type PaperSection } from "@/lib/api/papers"; import { formatQuestionNumber } from "@/lib/validation/numbering"; import { ContentPreview } from "./content-preview";
const msg=(e:unknown)=>e instanceof ApiError?e.body.detail:"Request failed / 操作失敗";
const instructionText=(v:PaperDetail["instructions_json"])=>Array.isArray(v)?v.join("\n"):v??"";
export default function PaperBuilder({token,paperId}:{token:string;paperId:string}){
 const [paper,setPaper]=useState<PaperDetail>(); const [library,setLibrary]=useState<Question[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string>(); const [busy,setBusy]=useState<string>(); const [addTo,setAddTo]=useState<PaperSection>(); const [selected,setSelected]=useState<string[]>([]); const [search,setSearch]=useState(""); const [preview,setPreview]=useState(false); const [metaEdit,setMetaEdit]=useState(false); const [exporting,setExporting]=useState<Record<string,boolean>>({});
 const load=useCallback(async()=>{setLoading(true);setError(undefined);try{const [p,q]=await Promise.all([getPaper(token,paperId),listQuestions(token)]);setPaper(p);setLibrary(q);}catch(e){setError(msg(e));}finally{setLoading(false);}},[token,paperId]); useEffect(()=>{void Promise.resolve().then(load);},[load]);
 const total=useMemo(()=>paper?.sections.reduce((sum,s)=>sum+s.questions.reduce((x,pq)=>x+Number(pq.marks_override??pq.question.marks),0),0)??0,[paper]);
 const persistQuestions=async(section:PaperSection,questions:PaperQuestion[])=>{if(!paper)return;setPaper({...paper,sections:paper.sections.map(s=>s.id===section.id?{...s,questions}:s)});setBusy(section.id);try{await putSectionQuestions(token,paper.id,section.id,questions.map(q=>({question_id:q.question_id,marks_override:q.marks_override==null?null:Number(q.marks_override)})));await refreshQuiet();}catch(e){toast.error(msg(e));await refreshQuiet();}finally{setBusy(undefined);}};
 const refreshQuiet=async()=>{try{setPaper(await getPaper(token,paperId));}catch(e){toast.error(msg(e));}};
 const moveQuestion=(s:PaperSection,index:number,delta:number)=>{const q=[...s.questions];const target=index+delta;if(target<0||target>=q.length)return;[q[index],q[target]]=[q[target],q[index]];void persistQuestions(s,q.map((item,i)=>({...item,position:i})));};
 const moveSection=async(index:number,delta:number)=>{if(!paper)return;const sections=[...paper.sections];const target=index+delta;if(target<0||target>=sections.length)return;[sections[index],sections[target]]=[sections[target],sections[index]];setPaper({...paper,sections});setBusy("sections");try{await Promise.all(sections.map((s,i)=>updateSection(token,paper.id,s.id,{position:i})));await refreshQuiet();}catch(e){toast.error(msg(e));await refreshQuiet();}finally{setBusy(undefined);}};
 const runExport=async(format:"docx"|"pdf")=>{setExporting(x=>({...x,[format]:true}));try{let record=await createExport(token,paperId,format);for(let i=0;i<60&&!["succeeded","failed"].includes(record.status);i++){await new Promise(r=>setTimeout(r,1500));record=await getExport(token,record.id);}if(record.status!=="succeeded")throw new Error(record.error_message||`${format.toUpperCase()} export timed out`);const blob=await downloadExport(token,record.id);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${paper?.title||"paper"}.${format}`;a.click();URL.revokeObjectURL(url);toast.success(`${format.toUpperCase()} ready / 已下載`);}catch(e){toast.error(msg(e) === "Request failed / 操作失敗" && e instanceof Error ? e.message : msg(e));}finally{setExporting(x=>({...x,[format]:false}));}};
 if(loading)return <div className="space-y-4" role="status">{[1,2,3].map(i=><div key={i} className="h-36 animate-pulse rounded-xl bg-muted"/>)}</div>; if(error||!paper)return <Card><CardContent><p role="alert" className="text-destructive">{error||"Paper not found / 找不到試卷"}</p><Button className="mt-4" variant="outline" onClick={()=>void load()}><RefreshCw className="size-4"/>Retry / 重試</Button></CardContent></Card>;
 const addSelected=async()=>{if(!addTo)return;const existing=new Set(addTo.questions.map(q=>q.question_id));const additions=library.filter(q=>selected.includes(q.id)&&!existing.has(q.id)).map((q,i)=>({question_id:q.id,question:q,position:addTo.questions.length+i,marks_override:null}));await persistQuestions(addTo,[...addTo.questions,...additions]);setAddTo(undefined);setSelected([]);};
 return <div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">{paper.title}</h1><p className="text-sm text-muted-foreground">{paper.subject} · {paper.level}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setPreview(true)}><Eye className="size-4"/>Preview / 預覽</Button><Button disabled={exporting.docx} onClick={()=>void runExport("docx")}><FileDown className="size-4"/>{exporting.docx?"DOCX…":"Export DOCX"}</Button><Button disabled={exporting.pdf} onClick={()=>void runExport("pdf")}><FileDown className="size-4"/>{exporting.pdf?"PDF…":"Export PDF"}</Button></div></header>
 <Card><CardHeader><div className="flex justify-between"><CardTitle>Paper details / 試卷資料</CardTitle><Button variant="outline" size="sm" onClick={()=>setMetaEdit(!metaEdit)}>{metaEdit?"Cancel / 取消":"Edit / 編輯"}</Button></div></CardHeader><CardContent>{metaEdit?<MetadataForm paper={paper} save={async input=>{try{setPaper(await updatePaper(token,paper.id,input));setMetaEdit(false);}catch(e){toast.error(msg(e));}}}/>:<div className="grid gap-2 text-sm sm:grid-cols-3"><p><b>Date / 日期:</b> {paper.paper_date||"—"}</p><p><b>Duration / 時間:</b> {paper.duration_minutes??"—"} min</p><p><b>Total / 總分:</b> <span className="text-lg font-semibold">{total}</span></p><p className="whitespace-pre-wrap sm:col-span-3"><b>Instructions / 指示:</b> {instructionText(paper.instructions_json)||"—"}</p></div>}</CardContent></Card>
 <div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Sections / 分部</h2><p className="text-sm text-muted-foreground">Reorder with keyboard-accessible up/down controls. Drag-and-drop is a follow-up.</p></div><Button onClick={async()=>{const title=window.prompt("Section title / 分部標題",`Section ${paper.sections.length+1} / 第${paper.sections.length+1}部`);if(!title)return;try{await addSection(token,paper.id,title,paper.sections.length);await refreshQuiet();}catch(e){toast.error(msg(e));}}}><Plus className="size-4"/>Add section</Button></div>
 {paper.sections.length===0?<div className="rounded-xl border border-dashed p-10 text-center">No sections / 尚未有分部</div>:paper.sections.map((section,si)=><Card key={section.id}><CardHeader><div className="flex flex-wrap items-center gap-2"><CardTitle className="flex-1">{section.title}</CardTitle><Button size="icon" variant="outline" aria-label={`Move ${section.title} up`} disabled={si===0||busy==="sections"} onClick={()=>void moveSection(si,-1)}><ArrowUp className="size-4"/></Button><Button size="icon" variant="outline" aria-label={`Move ${section.title} down`} disabled={si===paper.sections.length-1||busy==="sections"} onClick={()=>void moveSection(si,1)}><ArrowDown className="size-4"/></Button><Button variant="outline" onClick={async()=>{const title=window.prompt("Rename / 重新命名",section.title);if(title&&title!==section.title){try{await updateSection(token,paper.id,section.id,{title});await refreshQuiet();}catch(e){toast.error(msg(e));}}}}>Rename</Button><Button variant="outline" aria-label={`Delete ${section.title}`} onClick={async()=>{if(!window.confirm(`Delete ${section.title}? / 確定刪除？`))return;try{await deleteSection(token,paper.id,section.id);await refreshQuiet();}catch(e){toast.error(msg(e));}}}><Trash2 className="size-4"/></Button></div></CardHeader><CardContent className="space-y-3">
  {section.questions.length===0?<p className="rounded-lg border border-dashed p-6 text-center text-sm">No questions / 尚未加入題目</p>:section.questions.map((pq,qi)=><div key={pq.question_id} className="grid items-center gap-3 rounded-lg border p-3 sm:grid-cols-[3rem_1fr_9rem_auto]"><b>{pq.display_number||formatQuestionNumber(qi+1,paper.template_profile?.numbering_config_json?.question_style??"arabic-dot")}</b><div className="min-w-0"><p className="truncate font-medium">{pq.question.internal_title}</p><p className="text-xs text-muted-foreground">Library marks / 題庫分數: {Number(pq.question.marks)}</p></div><Label className="text-xs">Override / 覆寫<Input type="number" min={0} step="0.5" value={pq.marks_override??""} placeholder={String(Number(pq.question.marks))} onChange={e=>{const value=e.target.value===""?null:Number(e.target.value);setPaper({...paper,sections:paper.sections.map(s=>s.id===section.id?{...s,questions:s.questions.map((q,i)=>i===qi?{...q,marks_override:value}:q)}:s)});}} onBlur={e=>void persistQuestions(section,section.questions.map((q,i)=>i===qi?{...q,marks_override:e.target.value===""?null:Number(e.target.value)}:q))}/></Label><div className="flex"><Button size="icon" variant="ghost" disabled={qi===0||busy===section.id} aria-label="Move question up" onClick={()=>moveQuestion(section,qi,-1)}><ArrowUp className="size-4"/></Button><Button size="icon" variant="ghost" disabled={qi===section.questions.length-1||busy===section.id} aria-label="Move question down" onClick={()=>moveQuestion(section,qi,1)}><ArrowDown className="size-4"/></Button><Button size="icon" variant="ghost" aria-label="Remove question" onClick={()=>void persistQuestions(section,section.questions.filter((_,i)=>i!==qi))}><Trash2 className="size-4"/></Button></div></div>)}
  <Button variant="outline" onClick={()=>{setAddTo(section);setSearch("");setSelected([]);}}><Plus className="size-4"/>Add from library / 從題庫加入</Button></CardContent></Card>)}
 <LibraryDialog section={addTo} open={!!addTo} close={()=>setAddTo(undefined)} library={library} search={search} setSearch={setSearch} selected={selected} setSelected={setSelected} add={()=>void addSelected()}/><PreviewDialog open={preview} close={()=>setPreview(false)} paper={paper}/></div>;
}
function MetadataForm({paper,save}:{paper:PaperDetail;save:(v:{title:string;subject:string;level:string;paperDate:string;durationMinutes:number;instructions:string})=>Promise<void>}){const [v,setV]=useState({title:paper.title,subject:paper.subject,level:paper.level,paperDate:paper.paper_date??"",durationMinutes:paper.duration_minutes??60,instructions:instructionText(paper.instructions_json)});return <form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void save(v);}}>{(["title","subject","level","paperDate"] as const).map(k=><Label key={k}>{k}<Input type={k==="paperDate"?"date":"text"} value={v[k]} onChange={e=>setV({...v,[k]:e.target.value})}/></Label>)}<Label>Duration / 時間<Input type="number" value={v.durationMinutes} onChange={e=>setV({...v,durationMinutes:e.target.valueAsNumber})}/></Label><Label className="sm:col-span-2">Instructions / 指示<textarea className="mt-1 min-h-20 w-full rounded-md border p-3" value={v.instructions} onChange={e=>setV({...v,instructions:e.target.value})}/></Label><Button className="w-fit">Save / 儲存</Button></form>}
function LibraryDialog({section,open,close,library,search,setSearch,selected,setSelected,add}:{section?:PaperSection;open:boolean;close:()=>void;library:Question[];search:string;setSearch:(s:string)=>void;selected:string[];setSelected:(s:string[])=>void;add:()=>void}){const items=library.filter(q=>`${q.internal_title} ${q.subject} ${q.level}`.toLowerCase().includes(search.toLowerCase()));return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent><DialogHeader><DialogTitle>Add questions / 加入題目</DialogTitle><DialogDescription>Append to {section?.title}. Source questions are never modified.</DialogDescription></DialogHeader><Input placeholder="搜尋 Search: 幾何 / Geometry" value={search} onChange={e=>setSearch(e.target.value)}/><div className="max-h-72 space-y-2 overflow-auto">{items.length===0?<p className="p-5 text-center text-sm text-muted-foreground">No matching questions / 沒有相符題目</p>:items.map(q=><Label key={q.id} className="flex items-center gap-3 rounded border p-3"><input type="checkbox" checked={selected.includes(q.id)} onChange={e=>setSelected(e.target.checked?[...selected,q.id]:selected.filter(id=>id!==q.id))}/><span>{q.internal_title}<small className="block text-muted-foreground">{q.subject} · {Number(q.marks)} marks</small></span></Label>)}</div><DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button disabled={!selected.length} onClick={add}>Append {selected.length} / 加入</Button></DialogFooter></DialogContent></Dialog>}
function PreviewDialog({open,close,paper}:{open:boolean;close:()=>void;paper:PaperDetail}){const typography=paper.template_profile?.typography_config_json??{};return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent className="max-h-[94vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>預覽（approximate，非 Word 分页）</DialogTitle><DialogDescription>Browser typography is indicative only; download DOCX for final fidelity checking.</DialogDescription></DialogHeader><article className="mx-auto w-full max-w-[210mm] bg-white p-10 text-black shadow" style={{fontFamily:`${String(typography.chinese_font??"Noto Sans CJK TC")}, ${String(typography.latin_font??"Arial")}, sans-serif`,fontSize:`${Number(typography.base_font_size_pt??12)}pt`,lineHeight:Number(typography.line_spacing??1.5)}}><h1 className="mb-2 text-center text-xl font-bold">{paper.title}</h1><p className="mb-6 text-center">{paper.subject} · {paper.level}</p>{paper.sections.map(s=><section key={s.id} className="mb-6"><h2 className="mb-3 text-lg font-bold">{s.title}</h2>{s.questions.map((q,i)=><div key={q.question_id} className="mb-4 grid grid-cols-[2.5rem_1fr_auto] gap-2"><b>{q.display_number||formatQuestionNumber(i+1,paper.template_profile?.numbering_config_json?.question_style??"arabic-dot")}</b><div><ContentPreview content={q.question.content_json}/></div><span>({Number(q.marks_override??q.question.marks)})</span></div>)}</section>)}</article></DialogContent></Dialog>}
