"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Plus, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button"; import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"; import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { ApiError } from "@/lib/api/client"; import { createPaper, listPapers, type PaperInput, type PaperSummary } from "@/lib/api/papers"; import { listTemplates, type TemplateProfile } from "@/lib/api/templates";
const schema = z.object({ title: z.string().trim().min(1), subject: z.string().trim().min(1), level: z.string().trim().min(1), paperDate: z.string(), durationMinutes: z.number().int().positive(), instructions: z.string(), templateProfileId: z.string().min(1, "Select a template / 請選擇範本") });
const defaults: PaperInput = { title: "", subject: "", level: "", paperDate: "", durationMinutes: 60, instructions: "", templateProfileId: "" };
const msg = (e: unknown) => e instanceof ApiError ? e.body.detail : "Paper service unavailable / 無法連接試卷服務";
export default function PapersPage({ token }: { token: string }) {
 const router = useRouter(); const [items,setItems]=useState<PaperSummary[]>([]); const [templates,setTemplates]=useState<TemplateProfile[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string>(); const [open,setOpen]=useState(false); const [saveError,setSaveError]=useState<string>(); const form=useForm<PaperInput>({resolver:zodResolver(schema),defaultValues:defaults});
 const load=useCallback(async()=>{setLoading(true);setError(undefined);try{const [p,t]=await Promise.all([listPapers(token),listTemplates(token)]);setItems(p);setTemplates(t);}catch(e){setError(msg(e));}finally{setLoading(false);}},[token]); useEffect(()=>{void Promise.resolve().then(load);},[load]);
 const submit=form.handleSubmit(async v=>{setSaveError(undefined);try{const paper=await createPaper(token,v);setOpen(false);router.push(`/papers/${paper.id}`);}catch(e){setSaveError(msg(e));}});
 return <div className="space-y-6"><header className="flex items-start justify-between"><div><h1 className="text-2xl font-semibold">Papers / 試卷</h1><p className="text-sm text-muted-foreground">組合題目，然後匯出 DOCX 或 PDF。</p></div><Button disabled={!loading&&templates.length===0} onClick={()=>{form.reset(defaults);setOpen(true);}}><Plus className="size-4"/>Create / 建立</Button></header>
 {loading?<div className="space-y-3" role="status">{[1,2,3].map(i=><div key={i} className="h-24 animate-pulse rounded-xl bg-muted"/>)}</div>:error?<Card><CardContent><p role="alert" className="text-destructive">{error}</p><Button className="mt-4" variant="outline" onClick={()=>void load()}><RefreshCw className="size-4"/>Retry / 重試</Button></CardContent></Card>:templates.length===0?<Card><CardHeader><CardTitle>Create a template first / 請先建立範本</CardTitle><CardDescription>Papers require a formatting profile.</CardDescription></CardHeader><CardContent><Button asChild><Link href="/templates">Go to templates / 前往範本</Link></Button></CardContent></Card>:items.length===0?<div className="rounded-xl border border-dashed p-10 text-center">No papers yet / 尚未有試卷</div>:<div className="grid gap-3">{items.map(p=><Link key={p.id} href={`/papers/${p.id}`} className="rounded-xl border bg-card p-5 hover:bg-accent"><h2 className="font-semibold">{p.title}</h2><p className="mt-1 text-sm text-muted-foreground">{p.subject} · {p.level} · {p.paper_date||"No date / 未定日期"}</p></Link>)}</div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>New paper / 新增試卷</DialogTitle><DialogDescription>Mixed-language example: 中一數學 Form 1 Mathematics</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="Title / 標題" error={form.formState.errors.title?.message}><Input placeholder="期中考試 / Mid-term Examination" {...form.register("title")}/></Field><div className="grid grid-cols-2 gap-4"><Field label="Subject / 科目"><Input placeholder="數學 / Mathematics" {...form.register("subject")}/></Field><Field label="Level / 班級"><Input placeholder="中一 / Form 1" {...form.register("level")}/></Field><Field label="Date / 日期"><Input type="date" {...form.register("paperDate")}/></Field><Field label="Duration (minutes) / 時間"><Input type="number" min={1} {...form.register("durationMinutes",{valueAsNumber:true})}/></Field></div><Field label="Instructions / 指示"><textarea className="min-h-20 rounded-md border bg-background p-3 text-sm" placeholder="回答所有題目 / Answer all questions" {...form.register("instructions")}/></Field><Field label="Template / 範本" error={form.formState.errors.templateProfileId?.message}><select className="h-9 rounded-md border bg-background px-3" {...form.register("templateProfileId")}><option value="">Select / 選擇</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name} (v{t.version})</option>)}</select></Field>{saveError&&<p role="alert" className="text-sm text-destructive">{saveError}</p>}<DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel / 取消</Button><Button disabled={form.formState.isSubmitting}>{form.formState.isSubmitting?"Creating…":"Create / 建立"}</Button></DialogFooter></form></DialogContent></Dialog></div>;
}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <Label className="grid gap-2">{label}{children}{error&&<span className="text-sm text-destructive">{error}</span>}</Label>}
