"use client";

import { useCallback, useEffect, useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm, useWatch, type FieldPath } from "react-hook-form";
import { Copy, Pencil, Plus, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { ApiError } from "@/lib/api/client";
import { createTemplate, listTemplates, templatePayload, templateToForm, updateTemplate, uploadLogo, type TemplateImportResult, type TemplateProfile } from "@/lib/api/templates";
import { ImportWizard } from "./import-wizard";
import { templateDefaults, templateFormSchema, type TemplateFormValues } from "@/lib/validation/template";

const message = (e: unknown) => e instanceof ApiError ? e.body.detail : "Template service unavailable / 無法連接範本服務";

export default function TemplatesPage({ token }: { token: string }) {
  const [items, setItems] = useState<TemplateProfile[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<TemplateProfile>(); const [saveError, setSaveError] = useState<string>(); const [uploading, setUploading] = useState(false); const [review, setReview] = useState<TemplateImportResult>();
  const form = useForm<TemplateFormValues>({ resolver: zodResolver(templateFormSchema), defaultValues: templateDefaults });
  const previewValues = useWatch({ control: form.control });
  const load = useCallback(async () => { setLoading(true); setError(undefined); try { setItems(await listTemplates(token)); } catch (e) { setError(message(e)); } finally { setLoading(false); } }, [token]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const show = (item?: TemplateProfile, duplicate = false) => { setEditing(duplicate ? undefined : item); setSaveError(undefined); setReview(undefined); form.reset(item ? { ...templateToForm(item), name: duplicate ? `${item.name} Copy / 副本` : item.name, logoAssetId: item.logo_asset_id } : templateDefaults); setOpen(true); };
  const submit = form.handleSubmit(async (values) => { setSaveError(undefined); try { if (editing) await updateTemplate(token, editing.id, values); else await createTemplate(token, values); setOpen(false); await load(); } catch (e) { setSaveError(message(e)); } });
  const logo = async (file?: File) => { if (!file) return; setUploading(true); setSaveError(undefined); try { form.setValue("logoAssetId", (await uploadLogo(token, file)).id, { shouldDirty: true }); } catch (e) { setSaveError(message(e)); } finally { setUploading(false); } };
  return <div className="space-y-6"><header className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">Template profiles / 格式範本</h1><p className="text-sm text-muted-foreground">管理學校試卷的可重用格式。Reusable, constrained formatting profiles.</p></div><div className="flex items-center gap-2"><ImportWizard token={token} onImported={(values, draft) => { setEditing(undefined); setSaveError(undefined); setReview(draft); form.reset(values); setOpen(true); }} /><Button onClick={() => show()}><Plus className="size-4" />New / 新增</Button></div></header>
    {loading ? <Loading /> : error ? <ErrorCard error={error} retry={load} /> : items.length === 0 ? <Empty action={() => show()} /> : <div className="grid gap-4 sm:grid-cols-2">{items.map(item => <Card key={item.id}><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle>{item.name}</CardTitle><span className="rounded-full bg-secondary px-2 py-1 text-xs">v{item.version}</span></div><CardDescription>{item.school_name}</CardDescription></CardHeader><CardContent className="flex gap-2"><Button variant="outline" onClick={() => show(item)}><Pencil className="size-4" />Edit / Rename</Button><Button variant="outline" onClick={() => show(item, true)}><Copy className="size-4" />Duplicate</Button></CardContent></Card>)}</div>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[94vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle>{editing ? "Edit template / 編輯範本" : "New template / 新增範本"}</DialogTitle><DialogDescription>All measurements are validated before saving. 所有尺寸均會在儲存前驗證。</DialogDescription></DialogHeader>{review && (<div className="rounded-md border bg-muted/40 p-3 text-sm"><p className="font-medium">Imported from DOCX / 已從 DOCX 匯入 — 請核對後儲存</p><p className="mt-1">Confidence / 信心度: {Object.entries(review.confidence).map(([k, v]) => `${k}: ${Math.round(v * 100)}%`).join(" · ")}</p>{review.unmapped.length > 0 && (<p className="mt-1 text-amber-600">Needs review / 需核對: {review.unmapped.join(", ")}</p>)}</div>)}<Form {...form}><form onSubmit={submit} className="space-y-5" noValidate>
      <Group title="Identity / 基本資料"><TextField form={form} name="name" label="Template name / 範本名稱" placeholder="中一數學 / Form 1 Mathematics" /><TextField form={form} name="schoolName" label="School name / 學校名稱" placeholder="博雅書院 / Arche College" /><CheckField form={form} name="isActive" label="Active / 啟用" /><FormItem><FormLabel>Logo / 校徽</FormLabel><Input type="file" accept="image/png,image/jpeg,image/svg+xml" onChange={e => void logo(e.target.files?.[0])} /><p className="text-xs text-muted-foreground">{uploading ? "Uploading… / 上載中…" : previewValues.logoAssetId ? `Asset: ${previewValues.logoAssetId}` : "Optional / 選填"}</p></FormItem></Group>
      <Group title="Page / 頁面"><SelectField form={form} name="pageSize" label="Page size / 紙張" options={["A4","Letter"]} />{(["marginTop","marginRight","marginBottom","marginLeft"] as const).map((n, i) => <NumberField key={n} form={form} name={n} label={`${["Top 上","Right 右","Bottom 下","Left 左"][i]} margin (mm)`} min={5} max={50} />)}</Group>
      <Group title="Typography / 字體"><TextField form={form} name="chineseFont" label="Chinese font / 中文字體" placeholder="思源黑體 / Noto Sans CJK TC" /><TextField form={form} name="latinFont" label="Latin font / 英文字體" placeholder="Arial / 英文字體" /><NumberField form={form} name="baseFontSize" label="Base size (pt) / 基本字號" min={8} max={36} /><NumberField form={form} name="lineSpacing" label="Line spacing / 行距" min={1} max={3} step={0.1} /></Group>
      <Group title="Header & footer / 頁眉頁尾"><TextField form={form} name="headerText" label="Header / 頁眉" placeholder="期中考試 / Mid-term Examination" /><TextField form={form} name="footerText" label="Footer / 頁尾" placeholder="機密 Confidential / 第 1 頁" /><CheckField form={form} name="pageNumbers" label="Page numbers / 顯示頁碼" /></Group>
      <Group title="Section headings / 分部標題"><NumberField form={form} name="sectionFontSize" label="Font size (pt) / 字號" min={8} max={36} /><CheckField form={form} name="sectionBold" label="Bold / 粗體" /><SelectField form={form} name="sectionAlignment" label="Alignment / 對齊" options={["left","center","right"]} /></Group>
      <Group title="Questions / 題目"><SelectField form={form} name="questionNumberStyle" label="Question numbering / 題號" options={["1","1.","(1)","arabic-dot","lower-alpha","upper-alpha","roman"]} /><SelectField form={form} name="subQuestionStyle" label="Sub-question / 分題" options={["a","a.","(a)","arabic-dot","lower-alpha","upper-alpha","roman"]} /><SelectField form={form} name="marksDisplayStyle" label="Marks display / 分數位置" options={["inline","right","below"]} /><TextField form={form} name="marksFormat" label="Marks format / 分數格式" placeholder="({marks} marks)" /><NumberField form={form} name="spacingBeforeQuestion" label="Before (pt) / 題前距" min={0} max={50} /><NumberField form={form} name="spacingAfterQuestion" label="After (pt) / 題後距" min={0} max={50} /><NumberField form={form} name="answerSpaceLines" label="Answer lines / 答題行數" min={0} max={20} /></Group>
      <details className="rounded-lg border bg-muted/30 p-4"><summary className="cursor-pointer font-medium">JSON preview / 開發者預覽</summary><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(templatePayload({ ...templateDefaults, ...previewValues }), null, 2)}</pre></details>{saveError && <p role="alert" className="text-sm text-destructive">{saveError}</p>}<DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel / 取消</Button><Button disabled={form.formState.isSubmitting || uploading}>{form.formState.isSubmitting ? "Saving…" : "Save / 儲存"}</Button></DialogFooter>
    </form></Form></DialogContent></Dialog></div>;
}

type FormApi = ReturnType<typeof useForm<TemplateFormValues>>;
function Group({ title, children }: { title: string; children: React.ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{children}</CardContent></Card>; }
function TextField({ form, name, label, placeholder }: { form: FormApi; name: FieldPath<TemplateFormValues>; label: string; placeholder: string }) { return <FormField control={form.control} name={name} render={({ field }) => <FormItem><FormLabel>{label}</FormLabel><FormControl><Input placeholder={placeholder} {...field} value={String(field.value ?? "")} /></FormControl><FormMessage /></FormItem>} />; }
function NumberField({ form, name, label, min, max, step = 1 }: { form: FormApi; name: FieldPath<TemplateFormValues>; label: string; min: number; max: number; step?: number }) { return <FormField control={form.control} name={name} render={({ field }) => <FormItem><FormLabel>{label}</FormLabel><FormControl><Input type="number" min={min} max={max} step={step} {...field} value={Number(field.value)} onChange={e => field.onChange(e.target.valueAsNumber)} /></FormControl><FormMessage /></FormItem>} />; }
function SelectField({ form, name, label, options }: { form: FormApi; name: FieldPath<TemplateFormValues>; label: string; options: string[] }) { return <FormField control={form.control} name={name} render={({ field }) => <FormItem><FormLabel>{label}</FormLabel><FormControl><select className="h-9 rounded-md border bg-background px-3" {...field} value={String(field.value)}>{options.map(v => <option key={v}>{v}</option>)}</select></FormControl><FormMessage /></FormItem>} />; }
function CheckField({ form, name, label }: { form: FormApi; name: FieldPath<TemplateFormValues>; label: string }) { return <FormField control={form.control} name={name} render={({ field }) => <FormItem className="flex items-center gap-3 self-end pb-2"><FormControl><input type="checkbox" checked={Boolean(field.value)} onChange={field.onChange} className="size-4" /></FormControl><FormLabel>{label}</FormLabel><FormMessage /></FormItem>} />; }
function Loading() { return <div className="grid gap-4 sm:grid-cols-2" role="status">{[1,2].map(i => <div key={i} className="h-36 animate-pulse rounded-xl bg-muted" />)}</div>; }
function ErrorCard({ error, retry }: { error: string; retry: () => Promise<void> }) { return <Card><CardContent><p role="alert" className="text-destructive">{error}</p><Button variant="outline" className="mt-4" onClick={() => void retry()}><RefreshCw className="size-4" />Retry / 重試</Button></CardContent></Card>; }
function Empty({ action }: { action: () => void }) { return <div className="rounded-xl border border-dashed p-10 text-center"><p className="font-medium">No templates yet / 尚未有範本</p><Button className="mt-4" onClick={action}>Create first template / 建立首個範本</Button></div>; }
